### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by mul1sh** [keep-network/tbtc.js#49]
I'm getting the following syntax error, when I try to run the example deposit

```js
Boom boom time TypeError: tbtcConstantsContract.methods[constantGetter] is not a function
    at file:///Users/mul1sh/Desktop/tbtc.js/src/Constants.js:46:65
    at Array.map (<anonymous>)
    at Function.withConfig (file:///Users/mulish/Desktop/tbtc.js/src/Constants.js:45:27)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Function.withConfig (file:///Users/mulish/Desktop/tbtc.js/src/TBTC.js:39:23)
    at Object.withConfig (file:///Users/mulish/Desktop/tbtc.js/src/TBTC.js:96:12)
    at runExample (file:///Users/mulish/Desktop/tbtc.js/examples/deposit.js:25:16)
```

Kindly assist

**Comment by mul1sh** [comment]
It seems the commit causing issues is `1c169dd79d1047f562094f3a53b111f6b017860c` every commit before that works with `example.js`

**Comment by Shadowfiend** [comment]
Latest master should work, sorry about this---we got unsynced from some naming changes in the contracts.

There's one more issue we're dealing with regarding `utxoSize` vs `utxoValue` per keep-network/tbtc#667 as well, more to come.

**Comment by mul1sh** [comment]
@Shadowfiend no worries, thanks for the feedback, was just alerting you :)
